name: "ON FEATURE BRANCH DELETE"

on:
  delete:
    branches:
      - 'feature/**'

env:
  GITHUB_BRANCH: ${{ github.event.ref }}
  GITHUB_BRANCH_NAME_WITHOUT_SLASH: ${GITHUB_BRANCH##*/}

jobs:
  info:
  runs-on: ubuntu-latest
  steps:
    - name: Print GITHUB_BRANCH
      run: GITHUB_BRANCH - ${{ env.GITHUB_BRANCH }}
    - name: Print GITHUB_BRANCH_NAME_WITHOUT_SLASH
      run: GITHUB_BRANCH_NAME_WITHOUT_SLASH - ${{ env.GITHUB_BRANCH_NAME_WITHOUT_SLASH }}
